<div id="view-content">
    <a style="float: right; margin-top: 15px" href="<?php echo $this->url(array(), 'home'); ?>">Return to home page </a></br></br>
    <h3 style="text-align: center">Twój formularz został pomyślnie wysłany. Dziękujemy!</b></h3>
    <p style="margin-left: 20px">W ciągu 3 dni otrzymasz maila zwrotnego... </br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br></p>
</div>