<br /><br />
<div id="view-content">
    <p></p>
    <h3 style="text-align: center">Twój formularz został pomyślnie wysłany. Dziękujemy!</b></h3>
    <p style="margin-left: 20px">W ciągu 3 dni otrzymasz maila zwrotnego... </br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br></p>
    <a style="margin-left: 150px; margin-bottom: 20px" href="<?php echo $this->url(array(), 'home'); ?>">Return to home page </a>
</div>