<div id="content">
    <h1>Wydział Informatyki ZUT</h1>
    <p>Żołnierska 49<br />
        71-210 Szczecin<br />
        Zachodniopomorskie<br />
        Polska<br /><br />

        91 449 56 70, 91 449 55 18</br>
        91 449 59 90</br>
        <a style="text-decoration: none" href="http://www.wi.zut.edu.pl">www.wi.zut.edu.pl</a></br></p>

    <p>Dojazd</p>
    <h3>Autorzy</h3>
    <p>Studenci Informatyki (III rok, I stopień) na Wydziale Informatyki ZUT:</br>
        Agata Grabowska</br>
        Patryk Diak</p>
</div>

<div id="rightSide">
    <h3>Sidebar Heading</h3>
    <p>Informacje</p>
    <img src="img/kalendarz.png" height="152" width="163" />
    <h3>Sidebar Heading</h3>
    <p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki.</p>
</div>
