<div id="content">
        <h1>Wydział Informatyki ZUT</h1>
        <p>Żołnierska 49<br />
        71-210 Szczecin<br />
        Zachodniopomorskie<br />
        Polska</p>
        <p>Dojazd</p>
	<h3>Autorzy</h3>
	<p>Agata</p>
	<p>Patryk</p>
</div>
	
<div id="rightSide">
	<h3>Sidebar Heading</h3>
	<p>Informacje</p>
	<img src="img/kalendarz.png" height="152" width="163" />
	<h3>Sidebar Heading</h3>
	<p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki.</p>
</div>
