<div id="content">
	<h1>Tytuł</h1>
	<p>Informacje o wyposażeniu Wydziału / sal</p>
	<img src="img/sala(1).jpg" height="206" width="320" />
	<h3>[Wykaz]</h3>
	<p>Lista / tabela sal z informacjami o wyposażeniu 
	technicznym, klimatyzacji, liczbie miejsc, nagłośnieniu, możliwości 
	prowadzenia video-konferencji itd.</p>
</div>
	
<div id="rightSide">
	<h3>Sidebar Heading</h3>
	<p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki. Podjęte w Szczecinie badania zostają ukierunkowane na zastosowania komputerów w automatyzacji statków i sterowaniu flotą morską oraz na monitoring i diagnostykę maszyn, a następnie komputerowe wspomaganie projektowania i produkcji wyrobów jednostkowych.</p>
	<img src="img/kalendarz.png" height="152" width="163" />
	<h3>Sidebar Heading</h3>
	<p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki.</p>
</div>
