<div id="content">
	<h1>Idea</h1>
	<p>Pomysł opiera się na stworzeniu możliwości prezentowania się i 
	prowadzenia ciekawych<br />
	prelekcji kołom naukowym i przedstawicielom lokalnego biznesu z sfery 
	ICT. Idt.</p>
	<p>Opis ... </p>
	<img src="img/wi.jpg" height="181" width="280" />
	<img src="img/wi.jpg" height="181" width="280" />
	<h3>[Dodatkowe informacje</h3>
	<p>Wydział Informatyki jest najmłodszym, zaledwie 12-letnim, wydziałem Zachodniopomorskiego Uniwersytetu Technologicznego w Szczecinie, chociaż jednostka organizacyjna z jakiej powstał miała za sobą ponad dwudziestoletni okres rozwoju w dyscyplinie informatyka w strukturach Politechniki Szczecińskiej. Kierunek studiów Informatyka uruchomiony został już w roku 1991.</p>
</div>
	
<div id="rightSide">
	<h3>Sidebar Heading</h3>
	<p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki. Podjęte w Szczecinie badania zostają ukierunkowane na zastosowania komputerów w automatyzacji statków i sterowaniu flotą morską oraz na monitoring i diagnostykę maszyn, a następnie komputerowe wspomaganie projektowania i produkcji wyrobów jednostkowych.</p>
	<img src="img/kalendarz.png" height="152" width="163" />
	<h3>Sidebar Heading</h3>
	<p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki.</p>
</div>
