<div id="content">
	<h1>Tytuł</h1>
	<p>Wydział Informatyki jest najmłodszym, zaledwie 12-letnim, wydziałem Zachodniopomorskiego Uniwersytetu Technologicznego w Szczecinie, chociaż jednostka organizacyjna z jakiej powstał miała za sobą ponad dwudziestoletni okres rozwoju w dyscyplinie informatyka w strukturach Politechniki Szczecińskiej. Kierunek studiów Informatyka uruchomiony został już w roku 1991.</p>
	<p>Dzisiaj jest to wydział zorientowany na dynamiczną współpracę naukowo-badawczą z wiodącymi firmami IT. Studenci wydziału mają do dyspozycji doskonale wyposażone laboratoria, w tym jedyne w Polsce Centrum Edukacji i Badań HP oraz bibliotekę. Każdy użytkownik komputerowej sieci wydziałowej ma ciągły dostęp do danych i oprogramowania z dowolnego miejsca na świecie. Swoje pasje studenci mogą realizować w prężnie działających kołach naukowych, a liczne wydarzenia, nie tylko naukowe, odbywające się na wydziale są dobrą okazją do zdobywania nowych doświadczeń. Liczne seminaria i warsztaty organizowane i prowadzone przez wiodące firmy są okazją do zapoznania się z najnowszymi osiągnięciami i jednocześnie stanowią źródło informacji o potrzebach rynku pracy branży IT.</p>
	
        <?php
            foreach ($this->users as $it)
            {
                echo $it['username']; 
            }
        ?> 
        <img src="img/wi.jpg" height="181" width="280" />
	<img src="img/wi.jpg" height="181" width="280" />
	<h3>Tytuł</h3>
	<p>Wydział Informatyki jest najmłodszym, zaledwie 12-letnim, wydziałem Zachodniopomorskiego Uniwersytetu Technologicznego w Szczecinie, chociaż jednostka organizacyjna z jakiej powstał miała za sobą ponad dwudziestoletni okres rozwoju w dyscyplinie informatyka w strukturach Politechniki Szczecińskiej. Kierunek studiów Informatyka uruchomiony został już w roku 1991.</p>
</div>
	
<div id="rightSide">
	<h3>Sidebar Heading</h3>
	<p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki. Podjęte w Szczecinie badania zostają ukierunkowane na zastosowania komputerów w automatyzacji statków i sterowaniu flotą morską oraz na monitoring i diagnostykę maszyn, a następnie komputerowe wspomaganie projektowania i produkcji wyrobów jednostkowych.</p>
	<img src="img/kalendarz.png" height="152" width="163" />
	<h3>Sidebar Heading</h3>
	<p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki.</p>

</div>

