
<link rel='stylesheet' type='text/css' href='js/fullcalendar/fullcalendar.print.css' media='print' />

<?php echo $this->jQuery(); ?>
<script>
    $(function() {
        $( "#datepicker" ).datepicker();
    });
</script>

<script type='text/javascript'>

    $(document).ready(function() {
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();
        allDay: false;    
        $('#calendar').fullCalendar({
            
            eventClick: function(calEvent, jsEvent, view) {
                $.ajax(
                {
                    url: "/index/get-event",
                    data: { id : calEvent.id },
                    type: "POST",
                    success: function(response){ 
                        var parsedResponse = jQuery.parseJSON(response);
                        alert(parsedResponse.toString());
                        $('#fullTitle').html(parsedResponse.fullTitle)
                        $('#start').html(parsedResponse.start)
                        $('#end').html(parsedResponse.end)
                        $('#where').html(parsedResponse.where)
                        $('#descritpion').html(parsedResponse.descritpion)
                        $('#additional').html(parsedResponse.additional)
                        $('#authors').html(parsedResponse.authors)
                    }
                });
                var date_str = calEvent.start.getHours()+":" + calEvent.start.getMinutes() + " - " + calEvent.end.getHours()+":" + calEvent.end.getMinutes()
                $('#title').html(calEvent.title);
                $('#time').html(date_str);
                $('#myModal').reveal();
            },
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            weekends: false,
            editable: false,
            timeFormat: 'h:mm{ - h:mm}',
            events: <?php echo $this->eventsData ?>
          
        });
		
    });
</script>
<div id="myModal" class="reveal-modal">
    <div id ="fullTitle" class ="fullTitle">Full title</div>
    <div id ="start" class ="start">Start </div>
    <div id ="end" class ="end">Stop </div>
    <div id ="where" class ="where">Where</div>
    <div id ="description" class ="description">Descritpion</div>
    <div id ="additional" class ="additional">Additional</div>
    <div id ="authors" class ="authors">Authors</div>
</div>
<div id="content">
    <div id='calendar'></div>

</div>

<div id="rightSide">
    <h3>Najbliższe prelekcje:</h3>
    <p>10-12-2012: &quot;Java ...&quot;</p>
    <p>15-12-2012: &quot;PHP...&quot;</p>
    <p>19-01-2013: &quot;Scrum...&quot;</p>
    <p>25-01-2013: &quot;Współczesne ....&quot;</p>
    <img src="img/kalendarz.png" height="152" width="163" />
    <h3>Sidebar Heading</h3>
    <p>Korzenie Wydziału Informatyki sięgają roku 1971. Do pracy na Politechnice Szczecińskiej przychodzi Jerzy Sołdek. Wykorzystanie wyników prac i doświadczenia J. Sołdka wyznacza kierunki rozwoju informatyki.</p>
</div>
