<div>
    <a style="float: right; margin-top: 15px" href="<?php echo $this->url(array(), 'logout'); ?>">Log out </a></br></br>
    <p style="text-align: center;">Witaj w serwisie rejestracji sal wykładowych na Wydziale Informatyki!</br></br>
 
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br></p>
</div>