
<div>
    <a style="float: right; margin-top: 15px" href="<?php echo $this->url(array(), 'login'); ?>">Return to login </a></br></br>
    <p style="margin-left: 20px">IF YOU DID NOT HAVE AN  ACCOUNT:</br>
    The first time you login to access one of these accounts, you will need to do the following:
    Click on the link to the application above that you are attempting to access and enter your username...</br></br>

        
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br>
    Lorem Ipsum</br></p>
</div>