<br /><br />
<div>
	<p>IF YOU DID NOT HAVE AN  ACCOUNT:</br>
        The first time you login to access one of these accounts, you will need to do the following:
        Click on the link to the application above that you are attempting to access and enter your username...</p>
        <br />...<br />...<br />
        <a href="<?php echo $this->url(array(), 'login'); ?>"> Return to Login </a></p>
</div>